steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/gumroad-killer/cosmic:cloudbuild",
        ".",
      ]
images:
  - "us-east1-docker.pkg.dev/gumroad-killer/cosmic:cloudbuild"
